// <auto-generated />
namespace MyWpf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1019));
        
        string IMigrationMetadata.Id
        {
            get { return "202010190811202_10-19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
